version: 0.1.{build}-{branch}

image: Visual Studio 2017

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

environment:
  QT: C:\Qt\5.9.1\mingw53_32

build_script:
  - call "build/appveyor/build_windows.cmd"

platform:
  - x86
  - x64
  
configuration:
  - Debug
  - Release

deploy:
  provider: GitHub

