sudo: required
dist: trusty

before_install:
  - sudo apt-add-repository --yes ppa:beineri/opt-qt591-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y qt59[QTPACKAGE]

script:
  - source /opt/qt59/bin/qt59-env.sh
  - qmake